#!/bin/sh

set -e

# begin-remove-after: released:trixie
# protective diversion of files moved from / to /usr, to avoid file loss.
# Only for upgrades.
if [ "$1" = "upgrade" ]; then
    dpkg-divert --package usr-is-merged --no-rename \
        --divert /lib/udev/hwdb.d/20-sane.hwdb.usr-is-merged \
        --add /lib/udev/hwdb.d/20-sane.hwdb
    dpkg-divert --package usr-is-merged --no-rename \
        --divert /lib/udev/rules.d/60-libsane1.rules.usr-is-merged \
        --add /lib/udev/rules.d/60-libsane1.rules
    dpkg-divert --package usr-is-merged --no-rename \
        --divert /lib/udev/rules.d/99-libsane1.rules.usr-is-merged \
        --add /lib/udev/rules.d/99-libsane1.rules
fi
# end-remove-after

#if [ "$1" = "upgrade" ]; then
    # Add the scanner system group if it doesn't exist
    if ! getent group | grep -q "^scanner:"; then
	echo "Adding scanner group..."
	addgroup --quiet --system scanner || true
    fi
#fi
#DEBHELPER#

